### PR TITLE
Update Korean translation

### PR DESCRIPTION
**Pull request by sh-cho**
- Replaced some words in order to match with previously used words
  - window: 윈도우 ➡️ 창
  - display: 화면 ➡️ 디스플레이
- Fill empty strings
- Add translations

(더 나은 번역이 있으면 제안 부탁드립니다)

### CODE REVIEW

**Comment by rxhanson** [comment]
Thanks! Mind updating the text I just added for the Restore Default Shortcuts button dialog?

**Comment by sh-cho** [comment]
No problem

**Comment by sh-cho** [comment]
Where can I find the text?

**Comment by rxhanson** [comment]
I merged master into this branch, so it's at the bottom of the file. I might have more UI updates before this release gets pushed out, but I'll just go ahead and merge this when you're ready.

**Comment by sh-cho** [comment]
Thanks. Updated!

**Comment by rxhanson** [comment]
Awesome, thanks!!

**Pull request merged**
