### PR TITLE
Add configurable screen edge gaps

### PR DESCRIPTION
**Pull request by Middlerun**
Addresses issue https://github.com/rxhanson/Rectangle/issues/171

As discussed in the issue, the `WindowManager` adjusts `usableScreens.visibleFrameOfCurrentScreen` by invoking a function `ScreenEdgeGap.adjustVisibleFrame()` to reduce the bounds according to the configured gap sizes. The window calculations then use this value.

There are a few calculations that use the visible frames of the next/previous screens. In these cases they can't use `visibleFrameOfCurrentScreen`, so I've updated them to make their own calls to `ScreenEdgeGap.adjustVisibleFrame()`. I'm not super happy with that solution because I was hoping to keep that adjustment in one place for maintainability.

Another possibility would be to add a dictionary of screen frames to the `UsableScreens` struct (i.e. `visibleScreenFrames: Dictionary<NSScreen, CGRect>`), as a replacement for `visibleFrameOfCurrentScreen`. Then they can be adjusted for the gaps all in one go, and referenced from wherever.

### CODE REVIEW

**Comment by rxhanson** [comment]
At quick glance, this looks good. I'll test it out this weekend. I agree with your thoughts on the next displays actions. I'll give this a little thought as I test it out, too.

**Comment by rxhanson** [comment]
I got a chance to dig through it and I'm good with merging it in.

I have some thoughts about adjusting it so that we don't have to call the function everywhere we plan to move across screens, but that would require a decent amount of refactoring, which I'll spare you :)

Thanks for contributing! Feel free to message me on https://gitter.im if you're interested in a Hookshot or Multitouch license, as per the contribution policy.

**Comment by Middlerun** [comment]
Awesome! I'll message you soon.

It just occurred to me that the readme should be updated with the new config options. I didn't think to do that in the PR.

**Comment by rxhanson** [comment]
I didn't mention the readme because I prefer the readme be updated after the release goes out, not as part of this PR. If you wanted to create a new PR for the readme, it'd definitely be appreciated.

**Pull request merged**
