### PR TITLE
Update Chinese translation

### PR DESCRIPTION
**Pull request by groverlynn**
Drop redundant zh-Hant-TW as zh-Hant defaults to zh-Hant-TW.
Update zh-Hans, zh-Hant and zh-Hant-HK to use consistent Apple glossary.
Complete zh-Hant-HK localisation.
Correct several minor mistakes in zh-Hans, zh-Hant, and zh-Hant-HK.

### CODE REVIEW

**Comment by rxhanson** [comment]
> Drop redundant zh-Hant-TW as zh-Hant defaults to zh-Hant-TW.

I'll take your word for it :)

Thanks!

**Comment by ChiahongHong** [comment]
Hi, @groverlynn

There seems to be a variant Chinese character (異體字) here, `熒幕` here should be `螢幕`.

https://github.com/rxhanson/Rectangle/blob/9fd9e3975bb9cccefc140434012328813d59e925/Rectangle/zh-Hant.lproj/Main.strings#L430

**Comment by groverlynn** [comment]
@ChiahongHong Thanks for pointing out these. You are absolutely right.

**Comment by groverlynn** [comment]
> I rolled those minor updates in myself, but definitely check it and make sure things look ok.

They look okay to me.

**Comment by rxhanson** [comment]
Great, thanks.

**Pull request merged**
