### PR TITLE
MultiWindowManager.cascadeActiveAppWindowsOnScreen: resize activeApp …

### PR DESCRIPTION
**Pull request by rudifa**
…windows to the size of the first

### CODE REVIEW

**Comment by rudifa** [comment]
@rxhanson 
Hello, this is a small improvement on my previous PR :
- now the windows being cascaded are also resized to the size of the first window.

**Comment by rudifa** [comment]
Screenshot 2023-06-02 at 10 01 09 copy

**Comment by rxhanson** [comment]
Thanks. I'm planning on rolling out a release soon, probably sometime this week.

**Comment by rudifa** [comment]
Glad you accepted it.
R.

**Pull request merged**
