### PR TITLE
Update Italian locale

### PR DESCRIPTION
**Pull request by antiasi**
Hello, I would like to help you with the translation of Rectangle! I translated the missing lines, and also changed "abbreviazioni -> scorciatoie", shortcuts is closer to italian "scorciatoie", "abbreviazioni" is when you write for example Mr. instead of Mister, it's something else. I turned "check for updates automatically" in the shorter "aggiornamenti automatici" because the translated line in the app UI was overlapping with the "check for updates" button, it was too long. I hope you may find this changes useful, thank you for your great work with this app.

### CODE REVIEW

**Comment by rxhanson** [comment]
Thanks for the thorough update!

On this note, I think that the shortcut recorder still has the incorrect word for shortcuts since MASShortcut didn't push a cocoapods release with the update last year (see https://github.com/rxhanson/Rectangle/issues/157). I'll look into a MASShortcut update later when I have the time - I've been considering migrating to a different shortcuts library written in Swift which is why I've been putting off thinking about this.

**Comment by antiasi** [comment]
So the word "abbreviazione/i" instead of "scorciatoia/e" was choosen to be consistent with Apple translation, I can change the lines back if you want to, but in my opinion (whatever Apple says) shortcut is "scorciatoia" and this is the correct translation, "abbreviazione" is abbreviation, both in english and in italian the meanings are different.

**Comment by rxhanson** [comment]
I'm good with leaving it consistent with Apple. In my opinion it is better to have consistency with Apple than with MASShortcut, especially since the path ahead will be to either update MASShortcut (or just its translation) or to replace MASShortcut with https://github.com/sindresorhus/KeyboardShortcuts.

**Comment by antiasi** [comment]
ok, I'll update the file then.

**Pull request merged**
