### PR TITLE
Updated italian translation

### PR DESCRIPTION
**Pull request by antiasi**
I translated the new lines in Rectangle 0.49, I would like to ask you about the "Todo mode" translation because Todo in italian it's not very self-explanatory, maybe something like "In Evidenza" would be better in the italian translation, which explain the idea of a pinned app on the right of the screen.

### CODE REVIEW

**Comment by rxhanson** [comment]
I'm all for changing the name for Italian, but would it cause confusion if anyone were looking for information about Todo mode in the repo, but thinking it is instead "In Evidenza"? If you don't think that would be a problem or think it would be something that Italian users would still be able to figure out, then I'm good with the change.

**Comment by GiorgioRen** [comment]
As an Italian i think "Todo" doesn't make sense, "In Evidenza" is better to explain the feature, maybe "In primo piano" ("always on top" in english) would be better?

**Comment by rxhanson** [comment]
I think I'd be good with "In Evidenza", as "In primo piano" might imply that the window is actually pinned on top rather than reflowed around, since "always on top" is a common request that is not possible due to macOS restrictions. With that said, I am good with whichever translation. @antiasi let me know if you want to rework this one or just have me merge it as-is.

**Comment by antiasi** [comment]
I updated the translation using In Evidenza instead of Todo, you should find the main.strings updated, tested on my local Rectangle installation and looks fine

**Comment by rxhanson** [comment]
Thanks!

**Pull request merged**
