### PR TITLE
Add documentation regarding import/export functionality

### PR DESCRIPTION
**Pull request by manojkarthick**
Updated README.md with a line on how to use the JSON import/export functionality.

### CODE REVIEW

**Comment by rxhanson** [comment]
Thanks!

**Comment by caarlos0** [comment]
is it possible to export/import via command line as well? would be nice to automate the entire thing :)

**Comment by rxhanson** [comment]
@caarlos0 The only way to automate this currently is to directly modify the plist for the userdefaults, as mentioned in the Readme. Since userdefaults are cached, you'd have to make sure that the cache gets updated so that your changes take effect immediately for the plist route. (I don't remember off the top of my head the proper command for refreshing the cache).

I don't have the bandwidth to add command line interfacing with the JSON import/export functionality, but I would merge a PR for it.

**Comment by caarlos0** [comment]
Nice, thanks @rxhanson!

**Pull request merged**
