### PR TITLE
Execute action by URL

### PR DESCRIPTION
**Pull request by decodism**
For basic scripting.

### CODE REVIEW

**Comment by rxhanson** [comment]
Nice! I didn't think about that way to do it. I'll start sponsoring you through GitHub sponsors if you wanted to set it up.

**Comment by sentiasa** [comment]
Can you please show an example for this?

When I tried `open -g "rectangle://execute-action?name=left-half"`

```
No application knows how to open URL rectangle://execute-action?name=left-half (Error Domain=NSOSStatusErrorDomain Code=-10814 "kLSApplicationNotFoundErr: E.g. no application claims the file" UserInfo={_LSLine=1489, _LSFunction=runEvaluator}).
```

**Comment by rxhanson** [comment]
@sentiasa this likely means that macOS hasn't made the association with the app. Maybe try uninstalling the app and reinstalling, or restarting your Mac.

**Comment by sentiasa** [comment]
@rxhanson great, it worked. I run it in my terminal and it placed the terminal successfully. 

I was looking to achieve, for example, open phpstorm and place it left-half. Would this approach work with this? 
If so, how can I give application name to this command?

Maybe something like:
`open -g "rectangle://execute-action?name=left-half&app=phpstorm"`

Or is it not possible to achieve this with execute action command?

**Comment by rxhanson** [comment]
@sentiasa These commands in Rectangle are the equivalent of executing the keyboard shortcut; there is no support for associating an app with the command at this time.

You can achieve this in [Rectangle Pro](https://rectangleapp.com/pro) (paid), by creating an "App Layout" and triggering that App Layout via URL (see https://github.com/rxhanson/RectanglePro-Community#programmatically-triggering-window-sizes--positions)

For future conversation on this topic, please create a new discussion in GitHub.

**Pull request merged**
